import 'package:flutter/material.dart';
import 'package:font_awesome_flutter/font_awesome_flutter.dart';

final List<IconData> iconsData = [
  Icons.text_fields,
  FontAwesomeIcons.userAstronaut,
  Icons.fitness_center,
  Icons.account_balance,
  Icons.fastfood,
  FontAwesomeIcons.donate,
  FontAwesomeIcons.wineGlassAlt,
  Icons.domain,
  Icons.account_balance_wallet,
  FontAwesomeIcons.dollarSign,
  Icons.shopping_cart,
  Icons.radio,
  Icons.videogame_asset,
  Icons.local_laundry_service,
  Icons.flag,
  Icons.music_note,
  FontAwesomeIcons.pills,
  Icons.event_seat,
  Icons.free_breakfast,
  Icons.pets,
  FontAwesomeIcons.lightbulb,
  Icons.star,
  FontAwesomeIcons.coins,
  Icons.pool,
  Icons.healing,
  Icons.nature_people,
  Icons.time_to_leave,
  FontAwesomeIcons.book,
  Icons.restaurant,
  Icons.cake,
  Icons.local_florist,
  FontAwesomeIcons.chessRook,
  Icons.weekend,
  Icons.vpn_key,
  FontAwesomeIcons.building,
  Icons.import_contacts,
  Icons.flight_takeoff,
  FontAwesomeIcons.basketballBall,
  Icons.access_time,
  FontAwesomeIcons.cookieBite,
  Icons.adjust,
  Icons.save,
  Icons.child_care,
  Icons.highlight,
];

Map<String, IconData> categoriesMap = {
  'Cansel': Icons.close,
  'FastFood': Icons.fastfood,
  'Movie': Icons.local_movies,
  'Sports': Icons.sports_basketball,
  'Workout': Icons.fitness_center,
  'Running': Icons.directions_run_rounded,
  'Laundry': Icons.local_laundry_service,
};
