import 'package:bloc/bloc.dart';
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

class CategoryCreatingBloc extends Cubit<IconData?> {
  CategoryCreatingBloc() : super(null);

  void set(IconData category) => emit(category);

  bool get isNotEmpty => state != null;
}

List<IconData> iconList = [
  Icons.account_balance,
  Icons.account_balance_wallet,
  Icons.airport_shuttle,
  Icons.album,
  Icons.alarm,
  Icons.assistant_photo,
  Icons.attach_money,
  Icons.audiotrack,
  Icons.beach_access,
  Icons.book,
  Icons.brush,
  Icons.build,
  Icons.business_center,
  Icons.cake,
  Icons.camera_alt,
  Icons.camera_roll,
  Icons.casino,
  Icons.child_friendly,
  Icons.color_lens,
  Icons.directions_boat,
  Icons.directions_bike,
  Icons.directions_run,
  Icons.domain,
  Icons.email,
  Icons.explore,
  Icons.fastfood,
  Icons.filter_hdr,
  Icons.filter_vintage,
  Icons.flight_takeoff,
  Icons.fitness_center,
  Icons.free_breakfast,
  Icons.gamepad,
  Icons.golf_course,
  Icons.grade,
  Icons.graphic_eq,
  Icons.group,
  Icons.headset,
  Icons.home,
  Icons.keyboard,
  Icons.kitchen,
  Icons.language,
  Icons.laptop,
  Icons.local_activity,
  Icons.local_bar,
  Icons.local_dining,
  Icons.local_florist,
  Icons.local_grocery_store,
  Icons.local_movies,
  Icons.motorcycle,
  Icons.mouse,
  Icons.notifications,
  Icons.pan_tool,
  Icons.polymer,
  Icons.remove_red_eye,
  Icons.schedule,
  Icons.school,
  Icons.security,
  Icons.weekend,
  Icons.sentiment_dissatisfied,
  Icons.sentiment_neutral,
  Icons.sentiment_satisfied,
  Icons.sentiment_very_dissatisfied,
  Icons.sentiment_very_satisfied,
  Icons.settings,
  Icons.smartphone,
  Icons.spa,
  Icons.speaker,
  Icons.store,
  Icons.style,
  Icons.tablet,
  Icons.thumb_down,
  Icons.thumb_up,
  Icons.thumbs_up_down,
  Icons.toys,
  Icons.traffic,
  Icons.trip_origin,
  Icons.videocam,
  Icons.vpn_key,
  Icons.watch,
  Icons.wc,
  Icons.weekend,
  Icons.whatshot,
  Icons.widgets,
];

