// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTubj2k09At7WvKvyWnNKY3U66A8cIdDA',
    appId: '1:1069951947681:android:74d5c20daaa83b1e2871e0',
    messagingSenderId: '1069951947681',
    projectId: 'chatdiary-8688c',
    storageBucket: 'chatdiary-8688c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQwxjGEHVe_vlSYdlIXlvx01Tmmp1tidM',
    appId: '1:1069951947681:ios:f373e277d7f46fde2871e0',
    messagingSenderId: '1069951947681',
    projectId: 'chatdiary-8688c',
    storageBucket: 'chatdiary-8688c.appspot.com',
    iosClientId: '1069951947681-4vmuaf5vkntl42vi91n0l8192vtj1soo.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatDiary',
  );
}
