import 'package:flutter/material.dart';

abstract class IconList {
  static const List<IconData> iconList = [
    Icons.ac_unit,
    Icons.access_alarm,
    Icons.accessibility,
    Icons.account_balance_wallet,
    Icons.add,
    Icons.airline_seat_flat,
    Icons.airport_shuttle,
    Icons.battery_alert,
    Icons.contacts,
    Icons.details,
    Icons.directions_bike,
    Icons.directions_boat,
    Icons.directions_bus,
    Icons.directions_car,
    Icons.directions_railway,
    Icons.explicit,
    Icons.explore,
    Icons.exposure,
    Icons.free_breakfast,
    Icons.gamepad,
    Icons.games,
    Icons.gavel,
    Icons.kitchen,
    Icons.local_bar,
    Icons.local_cafe,
    Icons.local_car_wash,
    Icons.local_convenience_store,
    Icons.local_dining,
    Icons.local_drink,
    Icons.local_florist,
    Icons.warning,
    Icons.watch_later,
    Icons.wb_cloudy,
    Icons.wb_sunny,
    Icons.wc,
  ];
}
